In [1]:
import numpy as np

In [2]:
lst=[2,5,7,8]

In [3]:
np.array(lst)

array([2, 5, 7, 8])

In [5]:
np.array([lst,lst])

array([[2, 5, 7, 8],
       [2, 5, 7, 8]])

In [6]:
np.array([[2,4,6],[2,7,9]])

array([[2, 4, 6],
       [2, 7, 9]])

In [7]:
np.array([[2,4,6],[2,7,9],[3,-1,6]])

array([[ 2,  4,  6],
       [ 2,  7,  9],
       [ 3, -1,  6]])

In [8]:
10*np.eye(4)

array([[10.,  0.,  0.,  0.],
       [ 0., 10.,  0.,  0.],
       [ 0.,  0., 10.,  0.],
       [ 0.,  0.,  0., 10.]])

In [10]:
np.zeros(shape=(4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [11]:
5*np.ones(shape=(4,6))

array([[5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.]])

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(-5,10)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [21]:
np.arange(-5,11,3)

array([-5, -2,  1,  4,  7, 10])

In [23]:
np.arange(100,9,-5)

array([100,  95,  90,  85,  80,  75,  70,  65,  60,  55,  50,  45,  40,
        35,  30,  25,  20,  15,  10])

In [25]:
mat=np.random.randn(4,5)
mat

array([[ 1.24697564, -0.07288596,  0.99723346, -1.48378959,  1.06244227],
       [-1.66367239,  1.61829242, -1.35965162,  1.42543507,  1.10893913],
       [ 1.25774742, -1.06240977, -0.93017756,  0.4211683 , -1.07664978],
       [ 0.63618647, -1.83959769,  1.15250336, -1.06216512, -0.27129985]])

In [26]:
type(mat)

numpy.ndarray

In [27]:
mat.size

20

In [28]:
mat.shape

(4, 5)

In [30]:
mat.reshape(2,10).shape

(2, 10)

In [31]:
mat.dtype

dtype('float64')

In [33]:
arr=np.arange(50,70)

In [34]:
arr.shape

(20,)

In [35]:
arr[4]

54

In [36]:
arr[18]

68

In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [2]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[4:])

[5 6 7]


In [3]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[:4])

[1 2 3 4]


In [4]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


In [5]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


In [7]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


In [8]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,2])

[3 8]


In [39]:
import pandas as pd

df = pd.read_csv (r'C:\Users\ChoudAnt\Documents\Book1.csv')
print (df)

   Index  num1  num2
0      1   123   200
1      2   334   300
2      3   566   400
3      4   123   500
4      5   456   600
5      6   890   700
6      7   122   800
7      8   345   900
8      9   341  1000
9     10   400  1500


In [38]:
import pandas as pd

df = pd.read_csv (r'C:\\Users\\ChoudAnt\\Documents\\Book1.csv',usecols=["num1","num2"],nrows=5)
print (df)

   num1  num2
0   123   200
1   334   300
2   566   400
3   123   500
4   456   600


In [37]:
import pandas as pd

df = pd.read_csv (r'C:\\Users\\ChoudAnt\\Documents\\Book1.csv',usecols=["num1","num2"],nrows=5)
print (df)

   num1  num2
0   123   200
1   334   300
2   566   400
3   123   500
4   456   600


In [36]:
import pandas as pd

df = pd.read_csv (r'C:\\Users\\ChoudAnt\\Documents\\Book1.csv',header=0,usecols=["num1","num2"])
print (df)

   num1  num2
0   123   200
1   334   300
2   566   400
3   123   500
4   456   600
5   890   700
6   122   800
7   345   900
8   341  1000
9   400  1500


In [35]:
import pandas as pd

df = pd.read_csv ('C:\\Users\\ChoudAnt\\Documents\\Book1.csv',header=4)
print (df)

    4  123   500
0   5  456   600
1   6  890   700
2   7  122   800
3   8  345   900
4   9  341  1000
5  10  400  1500


In [31]:
import pandas as pd

df = pd.read_csv ('C:\\Users\\ChoudAnt\\Documents\\Book1.csv',index_col=["num2"],usecols=["num1","num2"],nrows=5)
print (df)

      num1
num2      
200    123
300    334
400    566
500    123
600    456


In [33]:
temperature=[30,31,32,33,34,35,36,37,38,39,40,41]
months=["jan","feb","march","april","may","june","july","aug","sep","oct","nov","dec"]
s1=pd.Series(temperature,months)

In [34]:
s1

jan      30
feb      31
march    32
april    33
may      34
june     35
july     36
aug      37
sep      38
oct      39
nov      40
dec      41
dtype: int64

In [40]:
s1[0]

30

In [42]:
s1[5]

35

In [43]:
s1[2:9]

march    32
april    33
may      34
june     35
july     36
aug      37
sep      38
dtype: int64

In [44]:
mapobj= {30: 300, 31: 310, 32:40,34:100}

In [45]:
s1.map(mapobj)

jan      300.0
feb      310.0
march     40.0
april      NaN
may      100.0
june       NaN
july       NaN
aug        NaN
sep        NaN
oct        NaN
nov        NaN
dec        NaN
dtype: float64